### ISSUE TITLE
Use RxJs instead of mobx

### ISSUE THREAD

**Issue by hansschenker** [urish/beat-machine#34]
Uri  - cool web-audio sample! What is the reason that you use mobx instead of RxJs?
thank's for publishing!!

**Comment by urish** [comment]
Thank you for the feedback hans. I'm using MobX in other projects, and I am familiar with it. Is there any good reason to switch to RxJS?

**Comment by hansschenker** [comment]
I think RxJs has more momentum on the web. Angular brought RxJs together
with Typescript to the forefront.

Typescript is more or less part of any big framework now. RxJs will follow
after people have more understanding for functional programming.
To my understanding RxJs backed up with Typescript could be the foundation
of a new Framework, solely based on "standard" web technology.
 In Angular Rxjs is half hearted used.

**Comment by benjamingr** [comment]
@hansschenker interesting, so the main issue in Angular is that there is not enough RxJS?

**Comment by hansschenker** [comment]
Yes Angular was in 2016, when Angular 2 was released (RxJs version 5), not
very experienced with RxJs.

Rob Wormald was pushing RxJs (main Author of NgRx).
 Rob Wormold is not on Angular team anymore.

RxJs with version 6 and 7 has matured a lot, but Angular is more or less
frozen since v10. Angular framework is done, there
will be only minor, not significant changes in next future.

**Comment by benjamingr** [comment]
@hansschenker do you think there are people "in the know" trying to prevent Angular from using more RxJS?

**Comment by hansschenker** [comment]
Minko Gechev member of Angular Team said, a survey on this topic said that
50% of people are for and 50% are against
more RxJs in Angular.
Angular as a Framework is done, use it as it is or move on.

**Comment by benjamingr** [comment]
i see this is marked "completed" but i don't think you moved to RxJS. Then again it looks like Angular moved to mobx like signals away from zones and RxJS. It looks like the people "in the know" got their way after all...
