### ISSUE TITLE
Bug: When pressing play for the first time metronome red light doesn't work

### ISSUE THREAD

**Issue by Franci5co5aoco** [urish/beat-machine#6]
Bug detected on `Chrome` and `Safari` works correctly on `Firefox`

**Steps to reproduce:**
- Navigate to: https://salsabeatmachine.org/ or http://localhost:4200/ (when app is running locally)
- Click play, metronome red light doesn't move
- Also sound stops if you wait four loops

**Expected:**
-When click play for the first time metronome red light moves and loop keeps playing until you stop it

![](https://user-images.githubusercontent.com/23215166/52086652-c5cfb200-25a7-11e9-9adf-e8c250dea56b.png)

**Comment by urish** [comment]
Thanks for reporting! This should have been fixed by 0145a7c2
